apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-postgres
  namespace: ci
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 5Gi
  volumeName: "pv-postgres"
