apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
  namespace: ci
stringData:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">

      <servers>
        <server>
          <id>coding-in.cloud-release</id>
          <username>iragogeta</username>
          <password>1samurai</password>
        </server>
        <server>
          <id>coding-in.cloud-snapshot</id>
          <username>iragogeta</username>
          <password>1samurai</password>
        </server>
      </servers>

    </settings>
