apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-gitea
  namespace: ci
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 10Gi
  volumeName: "pv-gitea"
