kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-sonar
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /k8s/sonar
