apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-jenkins
  namespace: ci
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 20Gi
  volumeName: "pv-jenkins"
