apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
      
      containers:
      - image: jenkins/jenkins:2.193-centos
        imagePullPolicy: IfNotPresent
        name: jenkins
        env:
          - name: JENKINS_HOME
            value: /var/jenkins_home
          - name: JENKINS_SLAVE_AGENT_PORT
            value: "50000"
        ports:
        - containerPort: 50000
          name: agent-request
        - containerPort: 8080
          name: webui
        - containerPort: 30202
        volumeMounts:
        - name: jenkins-persistent-storage
          mountPath: /var/jenkins_home/
      volumes:
      - name: jenkins-persistent-storage
        persistentVolumeClaim:
          claimName: claim-jenkins